/**
 * The branded "GST Report" PDF — company details, summary cards, B2B/B2C
 * breakdown, full invoice listing, monthly trend, and a QR code — shown to
 * the admin's CA for GST reconciliation / IT return prep. Distinct from the
 * GSTR-1 export (which is the raw return-schema B2B/B2CS tables) and from
 * the individual per-order invoice PDF.
 */
// pdfkit is CommonJS (`export =`) and the project has esModuleInterop off —
// see invoice.util.ts for why this import form is required.
import PDFDocument = require('pdfkit');
import * as QRCode from 'qrcode';

const BLUE = '#1d4ed8';
const BLUE_DARK = '#1e3a8a';
const DARK = '#0f172a';
const MUTED = '#64748b';
const BORDER = '#e2e8f0';
const PURPLE = '#7c3aed';
const ORANGE = '#ea580c';
const GREEN = '#16a34a';
const BG_TINT = '#f8fafc';

export interface GstReportCompany {
  legalName: string;
  brandName: string;
  gstin: string | null;
  pan: string | null;
  address: string | null;
  email: string;
  phone: string;
  website: string;
}

export interface GstReportSummary {
  totalGst: number;
  totalCgst: number;
  totalSgst: number;
  totalTaxable: number;
  invoiceCount: number;
  b2bCount: number;
  b2cCount: number;
  b2bGst: number;
  b2cGst: number;
  b2bTaxable: number;
  b2cTaxable: number;
}

export interface GstReportB2BRow {
  gstin: string;
  customerName: string;
  invoices: number;
  taxableValue: number;
  gstAmount: number;
}

export interface GstReportInvoiceRow {
  date: Date | string;
  invoiceNo: string;
  customerName: string;
  customerPhone: string | null;
  isB2b: boolean;
  gstin: string | null;
  taxableValue: number;
  cgst: number;
  sgst: number;
  gstAmount: number;
  gstPercent: number;
  totalPaid: number;
}

export interface GstReportMonthRow {
  label: string;
  invoices: number;
  taxableValue: number;
  gstAmount: number;
}

export interface GstReportData {
  generatedOn: Date;
  generatedBy: string;
  periodLabel: string;
  company: GstReportCompany;
  summary: GstReportSummary;
  b2bRows: GstReportB2BRow[];
  invoices: GstReportInvoiceRow[];
  monthly: GstReportMonthRow[];
  verifyText: string;
}

const inr = (n: number | null | undefined) =>
  `Rs ${(Number(n) || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const fmtDate = (d: Date | string) =>
  new Date(d).toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true });

const INVOICE_ROW_LIMIT = 1000;

export async function buildGstReportPdf(data: GstReportData): Promise<Buffer> {
  const qrPng = await QRCode.toBuffer(data.verifyText, { margin: 1, width: 200 });

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 30, bufferPages: true });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const L = 30;
      const R = doc.page.width - 30;
      const W = R - L;
      const BOTTOM = doc.page.height - 55;

      const ensureSpace = (needed: number) => {
        if (doc.y + needed > BOTTOM) doc.addPage();
      };

      // ── Header ──
      doc.fillColor(BLUE).font('Helvetica-Bold').fontSize(26).text('bookfleet', L, 32);
      doc.fillColor(MUTED).font('Helvetica-Bold').fontSize(7)
        .text('MOVE ANYTHING. ANYTIME.', L, 60, { characterSpacing: 1 });

      doc.fillColor(BLUE).font('Helvetica-Bold').fontSize(18).text('GST REPORT', L, 78);
      doc.fillColor(MUTED).font('Helvetica').fontSize(9)
        .text('GST collected on paid deliveries — split by B2B (with GSTIN) and B2C', L, 100, { width: 280 });

      const metaX = 330;
      const metaRow = (label: string, value: string, y: number) => {
        doc.fillColor(MUTED).font('Helvetica').fontSize(9).text(label, metaX, y, { width: 110 });
        doc.fillColor(DARK).font('Helvetica-Bold').fontSize(9).text(value, metaX + 115, y, { width: R - metaX - 115 });
      };
      metaRow('Report Generated On', fmtDate(data.generatedOn), 32);
      metaRow('Report Period', data.periodLabel, 48);
      metaRow('Generated By', data.generatedBy, 78);
      metaRow('Report Type', 'Summary + Detailed', 94);

      doc.moveTo(L, 130).lineTo(R, 130).lineWidth(1.5).strokeColor(BLUE).stroke();
      doc.y = 142;

      // ── Company details box ──
      const boxTop = doc.y;
      const boxH = 92;
      doc.roundedRect(L, boxTop, W, boxH, 8).lineWidth(1).strokeColor(BORDER).stroke();
      doc.fillColor(BLUE).font('Helvetica-Bold').fontSize(10).text('COMPANY DETAILS', L + 14, boxTop + 12);

      const c = data.company;
      const colA = L + 14, colB = L + 300;
      let ry = boxTop + 32;
      const field = (x: number, label: string, value: string, y: number) => {
        doc.fillColor(MUTED).font('Helvetica').fontSize(8.5).text(label, x, y, { width: 100 });
        doc.fillColor(DARK).font('Helvetica-Bold').fontSize(8.5).text(value || '—', x + 100, y, { width: 195 });
      };
      field(colA, 'Company Name', c.legalName, ry);
      field(colB, 'Registered Address', c.address || '—', ry);
      ry += 15;
      field(colA, 'Brand Name', c.brandName, ry);
      ry += 15;
      field(colA, 'GSTIN', c.gstin || 'Not configured', ry);
      field(colB, 'Email', c.email, ry);
      ry += 15;
      field(colA, 'PAN No.', c.pan || '—', ry);
      field(colB, 'Contact No.', c.phone, ry);

      doc.y = boxTop + boxH + 14;

      // ── GST summary cards ──
      const s = data.summary;
      const cards: { label: string; value: string; sub: string; color: string }[] = [
        { label: 'Total GST Collected', value: inr(s.totalGst), sub: `${s.invoiceCount} invoices`, color: GREEN },
        { label: 'B2B GST (with GSTIN)', value: inr(s.b2bGst), sub: `${s.b2bCount} B2B invoices`, color: PURPLE },
        { label: 'B2C GST (no GSTIN)', value: inr(s.b2cGst), sub: `${s.b2cCount} B2C invoices`, color: ORANGE },
        { label: 'CGST', value: inr(s.totalCgst), sub: '', color: BLUE },
        { label: 'SGST', value: inr(s.totalSgst), sub: '', color: PURPLE },
        { label: 'Taxable Value', value: inr(s.totalTaxable), sub: '', color: MUTED },
      ];
      const cardW = (W - 2 * 10) / 3;
      const cardH = 56;
      const cardsTop = doc.y;
      cards.forEach((card, i) => {
        const col = i % 3, row = Math.floor(i / 3);
        const cx = L + col * (cardW + 10);
        const cy = cardsTop + row * (cardH + 10);
        doc.roundedRect(cx, cy, cardW, cardH, 6).lineWidth(1).strokeColor(BORDER).stroke();
        doc.rect(cx, cy, 4, cardH).fill(card.color);
        doc.fillColor(MUTED).font('Helvetica-Bold').fontSize(7.5).text(card.label.toUpperCase(), cx + 12, cy + 8, { width: cardW - 20 });
        doc.fillColor(DARK).font('Helvetica-Bold').fontSize(15).text(card.value, cx + 12, cy + 22, { width: cardW - 20 });
        if (card.sub) doc.fillColor(MUTED).font('Helvetica').fontSize(7.5).text(card.sub, cx + 12, cy + 40, { width: cardW - 20 });
      });
      doc.y = cardsTop + 2 * (cardH + 10) + 8;

      // ── B2B + B2C summary tables (side by side) ──
      const halfW = (W - 12) / 2;
      const tableTop = doc.y;

      const drawMiniTable = (
        x: number,
        title: string,
        titleColor: string,
        headers: string[],
        colWidths: number[],
        rows: string[][],
        totalRow: string[],
      ) => {
        doc.fillColor(titleColor).font('Helvetica-Bold').fontSize(9).text(title, x, tableTop);
        let y = tableTop + 16;
        doc.rect(x, y, halfW, 16).fill(titleColor);
        let cx = x;
        doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(7.5);
        headers.forEach((h, i) => { doc.text(h, cx + 4, y + 4, { width: colWidths[i] - 4 }); cx += colWidths[i]; });
        y += 16;
        if (!rows.length) {
          doc.fillColor(MUTED).font('Helvetica').fontSize(8).text('No transactions in this period.', x + 4, y + 6);
          y += 20;
        } else {
          for (const row of rows) {
            cx = x;
            doc.fillColor(DARK).font('Helvetica').fontSize(7.5);
            row.forEach((val, i) => { doc.text(val, cx + 4, y + 4, { width: colWidths[i] - 4 }); cx += colWidths[i]; });
            y += 15;
            doc.moveTo(x, y).lineTo(x + halfW, y).lineWidth(0.5).strokeColor(BORDER).stroke();
          }
        }
        doc.rect(x, y, halfW, 16).fill(BG_TINT);
        cx = x;
        doc.fillColor(DARK).font('Helvetica-Bold').fontSize(7.5);
        totalRow.forEach((val, i) => { doc.text(val, cx + 4, y + 4, { width: colWidths[i] - 4 }); cx += colWidths[i]; });
        return y + 22;
      };

      const b2bColW = [halfW * 0.32, halfW * 0.28, halfW * 0.14, halfW * 0.13, halfW * 0.13];
      const b2bTaxTotal = s.b2bTaxable;
      const yAfterB2b = drawMiniTable(
        L, 'B2B SUMMARY (With GSTIN)', PURPLE,
        ['GSTIN', 'Customer', 'Inv.', 'Taxable', 'GST'],
        b2bColW,
        data.b2bRows.slice(0, 8).map((r) => [r.gstin, r.customerName, String(r.invoices), inr(r.taxableValue), inr(r.gstAmount)]),
        ['Total', '', String(s.b2bCount), inr(b2bTaxTotal), inr(s.b2bGst)],
      );

      const b2csColW = [halfW * 0.55, halfW * 0.15, halfW * 0.15, halfW * 0.15];
      const yAfterB2c = drawMiniTable(
        L + halfW + 12, 'B2C SUMMARY (Without GSTIN)', ORANGE,
        ['Customer', 'Inv.', 'Taxable', 'GST'],
        b2csColW,
        s.b2cCount ? [['Various Customers', String(s.b2cCount), inr(s.b2cTaxable), inr(s.b2cGst)]] : [],
        ['Total', String(s.b2cCount), inr(s.b2cTaxable), inr(s.b2cGst)],
      );
      doc.y = Math.max(yAfterB2b, yAfterB2c) + 6;

      // ── Invoice details table ──
      ensureSpace(40);
      doc.fillColor(BLUE_DARK).font('Helvetica-Bold').fontSize(10).text('INVOICE DETAILS', L, doc.y);
      doc.y += 16;

      const invCols = [
        { key: 'date', label: 'Date', w: 0.14 },
        { key: 'invoice_no', label: 'Invoice No.', w: 0.12 },
        { key: 'customer', label: 'Customer', w: 0.18 },
        { key: 'type', label: 'Type', w: 0.07 },
        { key: 'gstin', label: 'GSTIN', w: 0.13 },
        { key: 'taxable', label: 'Taxable', w: 0.1, right: true },
        { key: 'gst', label: 'GST', w: 0.11, right: true },
        { key: 'total', label: 'Total Paid', w: 0.11, right: true },
      ].map((c) => ({ ...c, w: c.w * W }));

      const drawInvHeader = () => {
        const headerY = doc.y;
        doc.rect(L, headerY, W, 16).fill(BLUE_DARK);
        let x = L;
        doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(7.5);
        for (const col of invCols) { doc.text(col.label, x + 4, headerY + 4, { width: col.w - 6, align: col.right ? 'right' : 'left' }); x += col.w; }
        doc.y = headerY + 18;
      };
      drawInvHeader();

      const invoices = data.invoices.slice(0, INVOICE_ROW_LIMIT);
      for (const row of invoices) {
        if (doc.y > BOTTOM) {
          doc.addPage();
          doc.y = 40;
          drawInvHeader();
        }
        const yy = doc.y;
        let x = L;
        const vals: Record<string, string> = {
          date: fmtDate(row.date),
          invoice_no: row.invoiceNo,
          customer: `${row.customerName}${row.customerPhone ? `\n${row.customerPhone}` : ''}`,
          type: row.isB2b ? 'B2B' : 'B2C',
          gstin: row.gstin || '—',
          taxable: inr(row.taxableValue),
          gst: `${inr(row.gstAmount)} (${row.gstPercent}%)`,
          total: inr(row.totalPaid),
        };
        doc.fillColor(row.isB2b ? PURPLE : ORANGE).font('Helvetica-Bold').fontSize(7);
        doc.fillColor(DARK).font('Helvetica').fontSize(7.5);
        for (const col of invCols) {
          doc.text(vals[col.key], x + 4, yy, { width: col.w - 6, align: col.right ? 'right' : 'left' });
          x += col.w;
        }
        doc.y = yy + 18;
        doc.moveTo(L, doc.y - 2).lineTo(R, doc.y - 2).lineWidth(0.5).strokeColor(BORDER).stroke();
      }
      // Total row
      if (doc.y > BOTTOM) { doc.addPage(); doc.y = 40; }
      doc.rect(L, doc.y, W, 16).fill(BG_TINT);
      doc.fillColor(DARK).font('Helvetica-Bold').fontSize(8)
        .text('Total', L + 4, doc.y + 4, { width: invCols[0].w + invCols[1].w + invCols[2].w + invCols[3].w + invCols[4].w - 6 });
      let tx = L + invCols[0].w + invCols[1].w + invCols[2].w + invCols[3].w + invCols[4].w;
      doc.text(inr(s.totalTaxable), tx + 4, doc.y + 4, { width: invCols[5].w - 6, align: 'right' }); tx += invCols[5].w;
      doc.text(inr(s.totalGst), tx + 4, doc.y + 4, { width: invCols[6].w - 6, align: 'right' }); tx += invCols[6].w;
      doc.text(inr(s.totalTaxable + s.totalGst), tx + 4, doc.y + 4, { width: invCols[7].w - 6, align: 'right' });
      doc.y += 22;
      doc.fillColor(MUTED).font('Helvetica').fontSize(7).text('* All amounts are in INR', L, doc.y);
      doc.y += 16;

      // ── Monthly breakdown + breakup tables ──
      ensureSpace(140);
      const halfW2 = (W - 12) / 2;
      const monthTop = doc.y;

      doc.fillColor(BLUE_DARK).font('Helvetica-Bold').fontSize(9).text('MONTHLY GST BREAKDOWN', L, monthTop);
      let my = monthTop + 16;
      const monthCols = [halfW2 * 0.4, halfW2 * 0.22, halfW2 * 0.19, halfW2 * 0.19];
      doc.rect(L, my, halfW2, 16).fill(BLUE_DARK);
      doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(7.5);
      ['Month', 'Invoices', 'Taxable', 'GST'].forEach((h, i) => {
        const x = L + monthCols.slice(0, i).reduce((a, b) => a + b, 0);
        doc.text(h, x + 4, my + 4, { width: monthCols[i] - 6 });
      });
      my += 18;
      for (const m of data.monthly) {
        doc.fillColor(DARK).font('Helvetica').fontSize(7.5);
        const vals = [m.label, String(m.invoices), inr(m.taxableValue), inr(m.gstAmount)];
        vals.forEach((v, i) => {
          const x = L + monthCols.slice(0, i).reduce((a, b) => a + b, 0);
          doc.text(v, x + 4, my + 3, { width: monthCols[i] - 6 });
        });
        my += 15;
      }
      doc.rect(L, my, halfW2, 16).fill(BG_TINT);
      doc.fillColor(DARK).font('Helvetica-Bold').fontSize(7.5);
      const monthTotals = ['Total', String(s.invoiceCount), inr(s.totalTaxable), inr(s.totalGst)];
      monthTotals.forEach((v, i) => {
        const x = L + monthCols.slice(0, i).reduce((a, b) => a + b, 0);
        doc.text(v, x + 4, my + 4, { width: monthCols[i] - 6 });
      });
      const yAfterMonth = my + 22;

      const bx = L + halfW2 + 12;
      doc.fillColor(BLUE_DARK).font('Helvetica-Bold').fontSize(9).text('GST SUMMARY (BREAKUP)', bx, monthTop);
      let by = monthTop + 16;
      doc.rect(bx, by, halfW2, 16).fill(BLUE_DARK);
      doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(7.5).text('Particulars', bx + 4, by + 4, { width: halfW2 * 0.65 - 6 });
      doc.text('Amount (Rs)', bx + halfW2 * 0.65 + 4, by + 4, { width: halfW2 * 0.35 - 6, align: 'right' });
      by += 18;
      const breakupRows: [string, string, boolean?][] = [
        ['Total Taxable Value', inr(s.totalTaxable), true],
        ['Total GST', inr(s.totalGst), true],
        ['   CGST', inr(s.totalCgst)],
        ['   SGST', inr(s.totalSgst)],
        ['   IGST', inr(0)],
        ['Total Invoices', String(s.invoiceCount), true],
        ['B2B GST', inr(s.b2bGst)],
        ['B2C GST', inr(s.b2cGst)],
      ];
      for (const [label, val, bold] of breakupRows) {
        doc.fillColor(DARK).font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(7.5)
          .text(label, bx + 4, by + 3, { width: halfW2 * 0.65 - 6 })
          .text(val, bx + halfW2 * 0.65 + 4, by + 3, { width: halfW2 * 0.35 - 6, align: 'right' });
        by += 14;
        doc.moveTo(bx, by - 1).lineTo(bx + halfW2, by - 1).lineWidth(0.4).strokeColor(BORDER).stroke();
      }

      doc.y = Math.max(yAfterMonth, by + 8) + 14;

      // ── Declaration + QR ──
      ensureSpace(90);
      const declTop = doc.y;
      const declH = 78;
      const qrSize = 78;
      doc.roundedRect(L, declTop, W, declH, 8).lineWidth(1).strokeColor(BORDER).stroke();
      doc.fillColor(BLUE).font('Helvetica-Bold').fontSize(9).text('DECLARATION', L + 14, declTop + 12);
      doc.fillColor(MUTED).font('Helvetica').fontSize(8)
        .text(
          `This GST Report is system generated from the ${data.company.brandName} Admin Panel based on paid deliveries ` +
          'and is intended for accounting and GST reconciliation purposes.',
          L + 14, declTop + 28, { width: W - qrSize - 50 },
        );
      doc.image(qrPng, R - qrSize - 12, declTop + (declH - qrSize) / 2, { width: qrSize, height: qrSize });
      doc.y = declTop + declH + 10;

      // ── Watermark + footer on every page ──
      // Disable auto-pagination for this finalization pass: we're drawing on a
      // fixed, already-determined set of pages, and text near the bottom
      // margin (e.g. footY + 12) can otherwise trip pdfkit's automatic
      // page-break and silently inject extra blank pages.
      doc.addPage = (() => doc) as typeof doc.addPage;
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);

        doc.save();
        doc.rotate(-30, { origin: [doc.page.width / 2, doc.page.height / 2] });
        doc.fillColor(BORDER).font('Helvetica-Bold').fontSize(46).opacity(0.5)
          .text(`${data.company.brandName.toUpperCase()} CONFIDENTIAL`, 0, doc.page.height / 2 - 20, {
            width: doc.page.width, align: 'center',
          });
        doc.opacity(1);
        doc.restore();

        const footY = doc.page.height - 40;
        doc.fillColor(BLUE).font('Helvetica-Bold').fontSize(9).text('bookfleet', L, footY);
        doc.fillColor(MUTED).font('Helvetica').fontSize(7.5)
          .text(`Generated by ${data.generatedBy} · ${data.company.website}`, L, footY + 12, { width: W - 80, align: 'center' });
        doc.text(`Page ${i - range.start + 1} of ${range.count}`, R - 80, footY + 12, { width: 80, align: 'right' });
      }

      doc.end();
    } catch (e) {
      reject(e);
    }
  });
}
